USE pathomanager;

DELETE FROM PATHO_ENUMS where enum_id in (select enum_id from patho_enums);

INSERT INTO PATHO_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES (1,'TEST','Blood Test');
INSERT INTO PATHO_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES (2,'TEST','Urine Test');
INSERT INTO PATHO_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES (3,'TEST','Blood Sugar Test');