-- CREATE SCHEMA `physio` ;

DROP TABLE IF EXISTS ADDRESSES;
DROP TABLE IF EXISTS PATIENTS;

CREATE TABLE ADDRESSES(
	ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    APARTMENT VARCHAR(255),
    STREET VARCHAR(255),
    AREA VARCHAR(255),
    CITY VARCHAR(255)
);

create table PATIENTS(
	PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(120),
    LAST_NAME VARCHAR(120),
    GENDER VARCHAR(6),
    DATE_OF_BIRTH DATE,
    BLOOD_GROUP VARCHAR(4),
    EXISTING_AILMENTS VARCHAR(255),
    ALLERGIES VARCHAR(255),
    MOBILE VARCHAR(10),
    EMAIL VARCHAR(150),
    OCCUPATION VARCHAR(255),
	ADDRESS_ID INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);


select * from ADDRESSES;
select * from PATIENTS;

CREATE TABLE HOSPITAL_ENUMS(
	ENUM_ID INT,
    ENUM_GROUP VARCHAR(100),
    ENUM_VALUE VARCHAR(200),
	UNIQUE(ENUM_GROUP,ENUM_VALUE)
);

INSERT INTO HOSPITAL_ENUMS VALUES(1, 'BLOOD_GROUP', 'A');
INSERT INTO HOSPITAL_ENUMS VALUES(2, 'BLOOD_GROUP', 'B');
INSERT INTO HOSPITAL_ENUMS VALUES(3, 'BLOOD_GROUP', 'A+');
INSERT INTO HOSPITAL_ENUMS VALUES(4, 'BLOOD_GROUP', 'B+');
