-- CREATE SCHEMA `physio` ;

DROP TABLE IF EXISTS ADDRESSES;
DROP TABLE IF EXISTS PATIENTS;

CREATE TABLE ADDRESSES(
	ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    APARTMENT VARCHAR(255),
    STREET VARCHAR(255),
    AREA VARCHAR(255),
    CITY VARCHAR(255)
);

create table PATIENTS(
	PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(120),
    LAST_NAME VARCHAR(120),
    GENDER VARCHAR(6),
    DATE_OF_BIRTH DATE,
    BLOOD_GROUP VARCHAR(4),
    EXISTING_AILMENTS VARCHAR(255),
    ALLERGIES VARCHAR(255),
    MOBILE VARCHAR(10),
    EMAIL VARCHAR(150),
    OCCUPATION VARCHAR(255),
	ADDRESS_ID INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);


select * from ADDRESSES;
select * from PATIENTS;
select * from PATIENTS where patient_Id = 1 or first_Name = 'asdf';


CREATE TABLE HOSPITAL_ENUMS(
	ENUM_ID INT PRIMARY KEY,
    ENUM_GROUP VARCHAR(100),
    ENUM_VALUE VARCHAR(200),
	UNIQUE(ENUM_GROUP,ENUM_VALUE)
);

DELETE FROM HOSPITAL_ENUMS WHERE ENUM_GROUP LIKE 'BLOOD_GROUP';

INSERT INTO HOSPITAL_ENUMS VALUES(1, 'BLOOD_GROUP', 'A+');
INSERT INTO HOSPITAL_ENUMS VALUES(2, 'BLOOD_GROUP', 'O+');
INSERT INTO HOSPITAL_ENUMS VALUES(3, 'BLOOD_GROUP', 'B+');
INSERT INTO HOSPITAL_ENUMS VALUES(4, 'BLOOD_GROUP', 'AB+');
INSERT INTO HOSPITAL_ENUMS VALUES(5, 'BLOOD_GROUP', 'A-');
INSERT INTO HOSPITAL_ENUMS VALUES(6, 'BLOOD_GROUP', 'O-');
INSERT INTO HOSPITAL_ENUMS VALUES(7, 'BLOOD_GROUP', 'B-');
INSERT INTO HOSPITAL_ENUMS VALUES(8, 'BLOOD_GROUP', 'AB-');


SELECT * FROM HOSPITAL_ENUMS;

CREATE TABLE PRESCRIPTIONS(
	PRESCRIPTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    PATIENT_ID INT,
    SYMPTOMS TEXT,
    TREATMENT TEXT,
    MEDICAL_TESTS TEXT,
    COMMENTS TEXT,
    CREATED_TIMESTAMP DATETIME,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

CREATE TABLE TREATMENTS(
	TREATMENT_ID INT PRIMARY KEY,
    TREATMENT_NAME VARCHAR(255),
    FEE DOUBLE(6, 2)
);

delete from Treatments where TREATMENT_ID < 10000;

INSERT INTO TREATMENTS values(1, 'Consultation + Examination', 400.00);
INSERT INTO TREATMENTS values(2, 'Consultation + Examination + Therapy Day 1', 600.00);
INSERT INTO TREATMENTS values(3, 'Short case - 10 Sessions', 3500.00);
INSERT INTO TREATMENTS values(4, 'Short case follow-up', 500.00);
INSERT INTO TREATMENTS values(5, 'Long case - 10 Sessions', 4800.00);
INSERT INTO TREATMENTS values(6, 'Long case follow-up', 500.00);

select * from treatments;