CREATE SCHEMA HMS;

USE HMS;

CREATE TABLE USER(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
	PHONE VARCHAR(20),
	MOBILE VARCHAR(10),
	EMAIL VARCHAR(200),
	PASS VARCHAR(20)
);

