drop schema if exists HOSPITAL;

create schema HOSPITAL;

use HOSPITAL;

CREATE TABLE HOSP_ENUMS(
	ENUM_ID INT PRIMARY KEY,
    ENUM_GROUP TEXT(100),
    ENUM_VALUE TEXT(200)
);

INSERT INTO HOSP_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES(1,'CITY', 'Bareilly');
INSERT INTO HOSP_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES(2,'CITY', 'Mumbai');
INSERT INTO HOSP_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES(3,'CITY', 'Pune');
INSERT INTO HOSP_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES(4,'CITY', 'Banglore');
INSERT INTO HOSP_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES(5,'CITY', 'Very long city name for testing');

-- departments in hospital

INSERT INTO HOSP_ENUMS (ENUM_ID, ENUM_GROUP, ENUM_VALUE) VALUES(101,'DEPARTMENT', 'OPD');


CREATE TABLE ADDRESSES(
	ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    APARTMENT TEXT(200),
    STREET TEXT(200),
    AREA TEXT(200),
    CITY INT,
    FOREIGN KEY (CITY) REFERENCES HOSP_ENUMS(ENUM_ID) 
);


CREATE TABLE PATIENTS(
	PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME TEXT(150),
    LAST_NAME TEXT(150),
    GENDER TEXT(6),
    DOB Date,
    EMAIL TEXT(200),
    MOBILE TEXT(10),
    PHONE TEXT(15),
    ADDRESS_ID INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);

select * from patients;

select * from addresses;
